#!/bin/bash

JSON_FILE="$1"
EVENT_TYPE="$2"
VERSION="$3"

PR_ACTION=$(jq -r ".action" $JSON_FILE)
PR_ID=$(jq -r ".number" $JSON_FILE)
COMMIT_ID=$(jq -r ".pull_request.head.sha" $JSON_FILE)
REPO_URL=$(jq -r ".repository.html_url" $JSON_FILE)
REPO_NAME=$(jq -r ".repository.name" $JSON_FILE)
COMMIT_SHA=$(echo ${COMMIT_ID} | cut -c1-7)
ORG_NAME=$(echo $REPO_URL | cut -d"/" -f4)

case "$PR_ACTION" in
  opened|edited)
    # Loading functions
    source $(dirname $0)/../functions/functions.sh

    echo "${GCP_KEY}" > /tmp/key.json
    echo "Building for ${PR_ACTION}, ${PR_ID}, ${REPO_URL}, ${COMMIT_ID}"
    gcloud auth activate-service-account --key-file=/tmp/key.json
    DATE=$(date +%s)
    curl -s -L --user "${GITHUB_USER}:${GITHUB_TOKEN}" "https://api.github.com/repos/${ORG_NAME}/${REPO_NAME}/zipball/pull/${PR_ID}/head" --output /tmp/${REPO_NAME}_${PR_ID}_${DATE}.zip
    #wget -O /tmp/${COMMIT_ID}.zip "${REPO_URL}/archive/${COMMIT_ID}.zip"
    mkdir /tmp/${REPO_NAME}_${PR_ID}_${DATE}
    unzip /tmp/${REPO_NAME}_${PR_ID}_${DATE}.zip -d /tmp/
    # Including hidden files in *
    shopt -s dotglob
    mv /tmp/${ORG_NAME}-${REPO_NAME}*/* /tmp/${REPO_NAME}_${PR_ID}_${DATE}
    cd /tmp/${REPO_NAME}_${PR_ID}_${DATE}
    if [ -s  cloudbuild.yaml ]; then
      echo "Found cloudbuild.yaml in source repository"
    elif ls -1 *.tf > /dev/null 2>&1 && cat *.tf | tr -d '\n' | grep -q 'terraform.*{'; then
      # Repo is for IAC, we copy the cloudbuild file for terraform
      echo "Found IAC terraform project"
      cp -af /app/cloudbuild_files/cloudbuild_terraform.yaml ./cloudbuild.yaml
    elif [ "${REPO_NAME}" == "lmes-fsa-customization" ]; then
      # Repo is for field service customization, we copy the cloudbuild file 
      echo "Found field service customization project"
      cp -af /app/cloudbuild_files/cloudbuild_field_service.yaml ./cloudbuild.yaml
    else
      echo "Copying generic file"
      cp -af /app/cloudbuild_files/cloudbuild.yaml .
    fi
    tar cvzf /tmp/${REPO_NAME}_${PR_ID}_${DATE}.tar.gz *
    # Excluding hidden files in *
    shopt -u dotglob
    gsutil cp /tmp/${REPO_NAME}_${PR_ID}_${DATE}.tar.gz gs://${GS_BUCKET_NAME}
    #gcloud config set builds/use_kaniko True
    gcloud config set project ${GCP_PROJECT_NAME}

    # Getting configuration of allinconfig and setting subs_allinconfig var
    get_configuration_allinconfig
    [ $? -ne 0 ] && { echo "ERROR: Not getting configuration of allinconfig"; exit 1; } 

    gcloud builds submit gs://${GS_BUCKET_NAME}/${REPO_NAME}_${PR_ID}_${DATE}.tar.gz --async --substitutions SHORT_SHA=${COMMIT_SHA},REPO_NAME=${REPO_NAME},_ORG_NAME=${ORG_NAME},COMMIT_SHA=${COMMIT_ID},TAG_NAME=${VERSION}${subs_allinconfig}
    ret=$?
  ;;
  *)
    echo "Skipping pull request event type $PR_ACTION"
    ret=0
  ;;
esac
 
exit $ret