#!/bin/bash

JSON_FILE="$1"
EVENT_TYPE="$2"
VERSION="$3"

REF_TYPE=$(jq -r ".ref" $JSON_FILE | cut -d"/" -f2)
if [ "${REF_TYPE}" == "tags" ]; then
    TAG_NAME=$(jq -r ".ref" $JSON_FILE | cut -d"/" -f3)
else
    BRANCH_NAME=$(jq -r ".ref" $JSON_FILE | cut -d"/" -f3)
fi
COMMIT_ID=$(jq -r ".head_commit.id" $JSON_FILE)
REPO_URL=$(jq -r ".repository.html_url" $JSON_FILE)
REPO_NAME=$(jq -r ".repository.name" $JSON_FILE)
COMMIT_SHA=$(echo ${COMMIT_ID} | cut -c1-7)
ORG_NAME=$(echo $REPO_URL | cut -d"/" -f4)

echo "${GCP_KEY}" > /tmp/key.json
rm -rf /tmp/${REPO_NAME}-${COMMIT_ID}
echo "Building for ${REF_TYPE}, ${BRANCH_NAME}, ${TAG_NAME}, ${COMMIT_ID}, ${REPO_URL}, ${REPO_URL}/archive/${COMMIT_ID}.zip"
gcloud auth activate-service-account --key-file=/tmp/key.json
curl -s -L --user "${GITHUB_USER}:${GITHUB_TOKEN}" ${REPO_URL}/archive/${COMMIT_ID}.zip --output /tmp/${COMMIT_ID}.zip
#wget -O /tmp/${COMMIT_ID}.zip "${REPO_URL}/archive/${COMMIT_ID}.zip"
#mkdir /tmp/${COMMIT_ID}
unzip -o /tmp/${COMMIT_ID}.zip -d /tmp/
# Including hidden files in *
shopt -s dotglob
#mv /tmp/${REPO_NAME}*/* /tmp/${COMMIT_ID}
cd /tmp/${REPO_NAME}-${COMMIT_ID}
tar cvzf /tmp/${COMMIT_ID}.tar.gz *
# Excluding hidden files in *
shopt -u dotglob
gsutil cp /tmp/${COMMIT_ID}.tar.gz gs://${GS_BUCKET_NAME}
#gcloud config set builds/use_kaniko True
gcloud config set project ${GCP_PROJECT_NAME}
if [ -z ${TAG_NAME} ]; then
    if ! [ -f cloudbuild.yaml ]; then
        cp /app/cloudbuild.yaml .
    fi
    gcloud builds submit gs://${GS_BUCKET_NAME}/${COMMIT_ID}.tar.gz --async --substitutions SHORT_SHA=${COMMIT_SHA},REPO_NAME=${REPO_NAME},_ORG_NAME=${ORG_NAME},COMMIT_SHA=${COMMIT_ID},TAG_NAME=${VERSION}
else
    if ! [ -f cloudbuild.yaml ]; then
        cp /app/cloudbuild_tag.yaml .
    fi
    gcloud builds submit gs://${GS_BUCKET_NAME}/${COMMIT_ID}.tar.gz --async --config cloudbuild.yaml --substitutions SHORT_SHA=${COMMIT_SHA},REPO_NAME=${REPO_NAME},_ORG_NAME=${ORG_NAME},COMMIT_SHA=${COMMIT_ID},TAG_NAME=$TAG_NAME
    #--substitutions COMMIT_SHA=${COMMIT_SHA},REPO_NAME=${REPO_NAME}  
fi
